"use client";

import React, { Suspense, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useAuth } from "@/lib/context/AuthContext";
import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { MfaStep } from "@/components/auth/MfaStep";
import { AlertCircle, Eye, EyeOff } from "lucide-react";

function isSafeRedirect(url: string | null): string | null {
  if (!url) return null;
  // Only allow same-origin relative paths (no protocol-relative or absolute URLs)
  return url.startsWith("/") && !url.startsWith("//") ? url : null;
}

export default function LoginPage() {
  return (
    <Suspense
      fallback={
        <div className="space-y-6 animate-fade-in">
          <div className="space-y-2">
            <div className="h-8 w-56 rounded-md bg-secondary animate-pulse" />
            <div className="h-4 w-72 rounded bg-secondary animate-pulse" />
          </div>
          <div className="h-10 w-full rounded-md bg-secondary animate-pulse" />
          <div className="h-10 w-full rounded-md bg-secondary animate-pulse" />
          <div className="h-10 w-full rounded-md bg-secondary animate-pulse" />
        </div>
      }
    >
      <LoginForm />
    </Suspense>
  );
}

function LoginForm() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [mfaToken, setMfaToken] = useState<string | null>(null);
  const { login } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim() || !password) return;
    setIsLoading(true);
    setError(null);
    try {
      const res = await login({ email: email.trim(), password });
      const redirect = isSafeRedirect(searchParams.get("redirect"));
      if (res.requires_mfa && res.mfa_token) {
        setMfaToken(res.mfa_token);
      } else {
        router.push(redirect || "/dashboard");
      }
    } catch (err: unknown) {
      setError(
        err instanceof Error
          ? err.message
          : "Invalid corporate credentials or unauthorized tenant"
      );
    } finally {
      setIsLoading(false);
    }
  };

  if (mfaToken) {
    return (
      <div className="space-y-6 animate-fade-in">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold font-serif tracking-tight text-foreground">
            Two-Factor Verification
          </h1>
          <p className="text-xs text-muted-foreground">
            Enter the 6-digit code generated by your corporate authenticator app.
          </p>
        </div>
        <MfaStep
          mfaToken={mfaToken}
          onSuccess={() => router.push(isSafeRedirect(searchParams.get("redirect")) || "/dashboard")}
          onCancel={() => setMfaToken(null)}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-2xl sm:text-3xl font-bold font-serif tracking-tight text-foreground">
          Sign in to Mistake
        </h1>
        <p className="text-xs sm:text-sm text-muted-foreground">
          Enter your work email and password to access your workspace.
        </p>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="space-y-4" noValidate>
        {error && (
          <div
            role="alert"
            className="p-3 rounded-lg bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 text-xs flex items-center gap-2"
          >
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <Input
          label="Work Email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="name@company.in"
          autoComplete="username"
          required
        />

        <div className="relative">
          <Input
            label="Password"
            type={showPassword ? "text" : "password"}
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="••••••••"
            autoComplete="current-password"
            required
            className="pr-10"
          />
          <button
            type="button"
            onClick={() => setShowPassword((v) => !v)}
            aria-label={showPassword ? "Hide password" : "Show password"}
            className="absolute right-2.5 top-[30px] p-1 text-muted-foreground hover:text-foreground transition-colors"
          >
            {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
          </button>
        </div>

        <div className="flex items-center justify-end">
          <span
            className="text-xs text-muted-foreground"
            title="Contact your workspace administrator to reset your password"
          >
            Forgot password? Contact your admin
          </span>
        </div>

        <Button type="submit" className="w-full h-10 font-semibold" isLoading={isLoading}>
          Sign In
        </Button>
      </form>

      {/* Switch to Signup */}
      <div className="text-center pt-2">
        <p className="text-xs text-muted-foreground">
          Don&apos;t have an account?{" "}
          <Link href="/signup" className="text-foreground hover:underline font-semibold">
            Create an account
          </Link>
        </p>
      </div>
    </div>
  );
}
