"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "@/lib/context/AuthContext";
import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { MfaStep } from "@/components/auth/MfaStep";
import { AlertCircle } from "lucide-react";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [mfaToken, setMfaToken] = useState<string | null>(null);
  const { login } = useAuth();
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    try {
      const res = await login({ email, password });
      if (res.requires_mfa && res.mfa_token) {
        setMfaToken(res.mfa_token);
      } else {
        router.push("/dashboard");
      }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Invalid corporate credentials or unauthorized tenant");
    } finally {
      setIsLoading(false);
    }
  };

  if (mfaToken) {
    return (
      <div className="space-y-6 animate-fade-in">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold font-serif tracking-tight text-foreground">
            Two-Factor Verification
          </h1>
          <p className="text-xs text-muted-foreground">
            Enter the 6-digit code generated by your corporate authenticator app.
          </p>
        </div>
        <MfaStep
          mfaToken={mfaToken}
          onSuccess={() => router.push("/dashboard")}
          onCancel={() => setMfaToken(null)}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-2xl sm:text-3xl font-bold font-serif tracking-tight text-foreground">
          Sign in to Mistake
        </h1>
        <p className="text-xs sm:text-sm text-muted-foreground">
          Enter your work email and password to access your workspace.
        </p>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="space-y-4">
        {error && (
          <div className="p-3 rounded-lg bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <Input
          label="Work Email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="name@company.in"
          required
        />

        <Input
          label="Password"
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder="••••••••"
          required
        />

        <Button type="submit" className="w-full h-10 font-semibold" isLoading={isLoading}>
          Sign In
        </Button>
      </form>

      {/* Switch to Signup */}
      <div className="text-center pt-2">
        <p className="text-xs text-muted-foreground">
          Don&apos;t have an account?{" "}
          <Link href="/signup" className="text-foreground hover:underline font-semibold">
            Create an account
          </Link>
        </p>
      </div>
    </div>
  );
}
