"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "@/lib/context/AuthContext";
import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { MfaStep } from "@/components/auth/MfaStep";
import { ArrowRight, Sparkles, AlertCircle } from "lucide-react";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [mfaToken, setMfaToken] = useState<string | null>(null);
  const { login } = useAuth();
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    try {
      const res = await login({ email, password });
      if (res.requires_mfa && res.mfa_token) {
        setMfaToken(res.mfa_token);
      } else {
        router.push("/dashboard");
      }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Invalid corporate credentials or unauthorized tenant");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDemoLogin = async (roleEmail: string) => {
    setEmail(roleEmail);
    setPassword("password123");
    setIsLoading(true);
    setError(null);
    try {
      await login({ email: roleEmail, password: "password123" });
      router.push("/dashboard");
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to launch demo workspace");
    } finally {
      setIsLoading(false);
    }
  };

  if (mfaToken) {
    return (
      <div className="space-y-6 animate-fade-in">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold font-serif tracking-tight text-foreground">
            Two-Factor Verification
          </h1>
          <p className="text-xs text-muted-foreground">
            Enter the 6-digit code generated by your corporate authenticator app.
          </p>
        </div>
        <MfaStep
          mfaToken={mfaToken}
          onSuccess={() => router.push("/dashboard")}
          onCancel={() => setMfaToken(null)}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-2xl sm:text-3xl font-bold font-serif tracking-tight text-foreground">
          Sign in to your ledger
        </h1>
        <p className="text-xs sm:text-sm text-muted-foreground">
          Enter your corporate credentials to access the audit investigation workspace.
        </p>
      </div>

      {/* 1-Click Fast-Track Demo Access */}
      <div className="p-3.5 rounded-xl border border-border/60 bg-muted/20 space-y-2">
        <div className="flex items-center justify-between text-xs">
          <span className="font-semibold text-foreground flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5 text-amber-500" /> Evaluation Mode
          </span>
          <span className="text-[11px] text-muted-foreground font-mono">1-Click Fast Track</span>
        </div>
        <button
          type="button"
          onClick={() => handleDemoLogin("aditya.verma@acmemfg.in")}
          className="w-full py-2 px-3 rounded-lg border border-border/60 bg-card hover:bg-muted/80 text-foreground text-xs font-medium flex items-center justify-between transition-colors"
        >
          <span>Sign in as <strong className="font-semibold">Lead Auditor</strong> (Acme Mfg)</span>
          <ArrowRight className="w-3.5 h-3.5 text-muted-foreground" />
        </button>
      </div>

      <div className="relative flex items-center justify-center">
        <div className="border-t border-border/50 w-full" />
        <span className="bg-background px-3 text-[11px] font-mono text-muted-foreground uppercase absolute">
          or continue with email
        </span>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit} className="space-y-4">
        {error && (
          <div className="p-3 rounded-lg bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <Input
          label="Corporate Work Email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="name@company.in"
          required
        />

        <Input
          label="Password"
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder="••••••••"
          required
        />

        <Button type="submit" className="w-full h-10 font-semibold" isLoading={isLoading}>
          Sign in to Workspace
        </Button>
      </form>

      {/* Switch to Signup */}
      <div className="text-center pt-2">
        <p className="text-xs text-muted-foreground">
          New enterprise organization?{" "}
          <Link href="/signup" className="text-foreground hover:underline font-semibold">
            Create tenant account
          </Link>
        </p>
      </div>
    </div>
  );
}
